version: '3.7'

services:
  app:
    image: phatnguyen1812/qldapm:latest
    ports:
      - '3000:3000'

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - app